// Build script: vendors JS/CSS libraries, generates icon + color data, and
// compiles the Tailwind stylesheet into src/tungsten/static/tungsten.
import fs from "node:fs";
import path from "node:path";
import { execSync } from "node:child_process";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const root = path.resolve(import.meta.dirname, "..");
const pkg = path.join(root, "src", "tungsten");
const out = path.join(pkg, "static", "tungsten");
const vendor = path.join(out, "vendor");
fs.mkdirSync(vendor, { recursive: true });

const nm = (p) => path.join(import.meta.dirname, "node_modules", p);
const copies = {
  "htmx.min.js": "htmx.org/dist/htmx.min.js",
  "alpine.min.js": "alpinejs/dist/cdn.min.js",
  "chart.umd.min.js": "chart.js/dist/chart.umd.min.js",
  "trix.umd.min.js": "trix/dist/trix.umd.min.js",
  "trix.css": "trix/dist/trix.css",
  "tom-select.complete.min.js": "tom-select/dist/js/tom-select.complete.min.js",
  "tom-select.css": "tom-select/dist/css/tom-select.css",
};
for (const [dest, src] of Object.entries(copies)) {
  fs.copyFileSync(nm(src), path.join(vendor, dest));
}

// Icons: { name: "<inner svg markup>" }
const nodes = JSON.parse(fs.readFileSync(nm("lucide-static/icon-nodes.json"), "utf8"));
const esc = (v) => String(v).replace(/&/g, "&amp;").replace(/"/g, "&quot;");
const icons = {};
for (const [name, children] of Object.entries(nodes)) {
  icons[name] = children
    .map(([tag, attrs]) => `<${tag} ${Object.entries(attrs).map(([k, v]) => `${k}="${esc(v)}"`).join(" ")}/>`)
    .join("");
}
fs.writeFileSync(path.join(pkg, "support", "icons.json"), JSON.stringify(icons));

// Tailwind palettes -> Python
const colors = require("tailwindcss/colors");
const skip = new Set(["inherit", "current", "transparent", "black", "white",
  "lightBlue", "warmGray", "trueGray", "coolGray", "blueGray"]);
let py = "# Generated by frontend/build.mjs - Tailwind CSS default palettes.\n\nPALETTES: dict[str, dict[int, str]] = {\n";
for (const name of Object.keys(colors)) {
  if (skip.has(name)) continue;
  const shades = colors[name];
  if (typeof shades !== "object") continue;
  py += `    "${name}": {` + Object.entries(shades).map(([k, v]) => `${k}: "${v}"`).join(", ") + "},\n";
}
py += "}\n";
fs.writeFileSync(path.join(pkg, "support", "palettes.py"), py);

execSync(
  `npx tailwindcss -c tailwind.config.js -i input.css -o ${path.join(out, "tungsten.css")} --minify`,
  { stdio: "inherit", cwd: import.meta.dirname },
);
console.log("Built Tungsten assets.");
